language: node_js
node_js:
  - "node"

install:
  - npm install
  - npm install -g firebase-tools

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build:dev
  - npm test

after_success:
  - npm run build:deploy
  - firebase deploy --token $FIREBASE_TOKEN