language: node_js
node_js:
  - "node"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build:dev
  - npm test

after_succss:
  - npm run deploy --email ${FIREBASE_BENSRESUME_USERNAME} --password ${FIREBASE_BENSRESUME_PASSWORD}