language: node_js
node_js:
  - "lts/*"

install:
  - npm install
  - cd functions && npm install && cd ..
  - npm install -g firebase-tools

services:
  - xvfb

# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start

script:
  - npm run build:prod
  - npm test

after_success:
  - npm run build:deploy && firebase deploy --token $FIREBASE_TOKEN
